version: '3.8'

services:
 app:
   build:
     context: .
     dockerfile: Dockerfile
   ports:
     - "8080:8080" # Map container port 8080 to host port 8080
   environment:
     - ASPNETCORE_ENVIRONMENT=Development
   volumes:
     - .:/app # Mount the current directory to /app in the container
   restart: always
