version: '3.8'

services:
 simpliapi:
   build:
     context: .
     dockerfile: Dockerfile
   image: simpli_api
   container_name: simpli_api_container
   ports:
     - "8080:8080" 
   environment:
     - ASPNETCORE_ENVIRONMENT=Development
   networks:
     - api_network

networks:
  api_network:
    driver: bridge